# Study Topics 

We want to simulate the real-world situation where people in your profession circle make change for their career. In the last 6 mths there are around 10 people

## Assumptions Made

1. Assume the distribution of years of experience in a particular person's circle follows normal distribution with mean of the same yrs of experience of the person and regular stdev of 1.0.
2. Assume that the average time for a person to switch job is around 3 yrs. So the distribution is a normal distribution follows normal distribution with mean as 5 and stdev as 1.0.
3. In this study, we constrain the interested time window into 1 year or 12 months. 
4. We assume the number of people a person know relatively intimately is around 50 people. 
5. For people across different yrs of experience will at any time point will have 50% chance of looking for a new job.
6. Assume the average preparation time is 6 month. 
7. Assume the people who are looking and prepared have 35% chance to find the job they want and the other also want them. 
8. Assume that the preparation could start at any time point in the year which implies a uniform distribution.





**Question to answer** 
we are trying to figure out how many people will leave the circle based on the simulation. 

## Questions

1. Years of experience in total or in one company? - in this case, I think we should just concern the years of experience in one company
2. The possibility of change 

# Simulation 

In [2]:
import numpy as np
import matplotlib.pyplot as plt

from scipy import stats
import seaborn as sns

sns.set(color_codes = True)
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

## Hyperparameters

In [36]:
num_pop = 50

avg_exp = 3
stdev_exp = 1.0

avg_ts = 3
stdev_ts = 1.0

## Simulate the yrs of experience

In [32]:

print('number of people who are looking for a new role at any time point is %s' % len(exp_pop))


number of people who are looking for a new role at any time point is 25


## Simulate the starting and the ending date of preparation 

In [13]:
sta_prep = np.random.uniform(low=1, high =12, size = int(num_pop/2))
sta_prep

number of people who are looking for a new role at any time point is 25


array([ 3.88640374,  1.18731102,  4.69681852,  3.91669662, 10.56927473,
        3.35322962, 10.0645978 , 10.26291554,  4.72275857,  1.63505095,
        8.98550906,  1.8926978 ,  5.48752222,  9.68645534,  5.06749557,
        7.67968734, 10.07513182,  1.94742875,  8.95583374,  2.3203532 ,
       10.80285032,  6.08570196,  5.37166865, 11.30578867,  4.77441639])

In [28]:
end_prep = sta_prep + np.random.normal(6,3,int(num_pop/2))
end_prep

array([12.28721543,  5.33370581, 10.07406445, 12.33745636, 16.48907623,
       13.87212338, 12.48749029, 15.17962678, 11.5632395 ,  6.58539856,
       17.7583912 ,  9.37638134,  8.43416942, 16.32597478, 12.80301868,
       11.11470319, 17.55689359,  6.38241675, 15.25118097,  7.40376509,
       20.50896899, 11.42316307, 12.51274055, 19.18874817, 11.35696889])

**For those who have the end date > 12 will be ruled out becasue they pass 1 yr boundary in this case.**

In [29]:
# 1 year window size
end_pop = [i for i in end_prep if i <= 18]
len(end_pop)

23

In [30]:
# first 6 month window size 
halfyr_end_pop = [i for i in end_prep if i <= 12]
len(halfyr_end_pop)

11

## Ramdon sample these people years of experience in the company

In [37]:
exp_pop = np.random.normal(avg_exp,stdev_exp,len(end_pop))
exp_pop

array([2.09432981, 2.68942574, 1.25071976, 2.43566958, 4.88915952,
       2.10915182, 3.66252267, 3.56531982, 1.52898182, 1.9087079 ,
       3.34045582, 2.7274915 , 1.46968225, 2.14516995, 2.51815779,
       2.87190151, 3.54366273, 3.164418  , 3.67094595, 2.63971364,
       2.76862235, 1.28466399, 4.33625716])

In [38]:
pop_w_3more_exp = [i for i in exp_pop if i >= 3]
len(pop_w_3more_exp)

8

In [39]:
pop_w_3less_exp = [i for i in exp_pop if i < 3]
len(pop_w_3less_exp)

15